on:
  push:
  pull_request:

name: Checks

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: 'Install yarn'
        run: npm install -g yarn

      - name: Install dependencies
        run: |
          yarn

      - name: 'format and lint'
        run: |
          yarn run format
          yarn run lint

      - name: 'Build'
        run: |
          yarn run build

      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
